version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: sigeim-db
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: sigeim
      MYSQL_USER: sigeim_user
      MYSQL_PASSWORD: password_sigeim
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigeim-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sigeim
      SPRING_DATASOURCE_USERNAME: sigeim_user
      SPRING_DATASOURCE_PASSWORD: password_sigeim
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
networks:
  default:
    name: sigeim-network
    driver: bridge
